// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKI6LDUimJvKiBOFd2HFqs-sc7YQI_1w',
    appId: '1:639418752677:web:1eb5047df9c990da05774c',
    messagingSenderId: '639418752677',
    projectId: 'clipsync-44cea',
    authDomain: 'clipsync-44cea.firebaseapp.com',
    storageBucket: 'clipsync-44cea.firebasestorage.app',
    measurementId: 'G-3MH18D2DMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_mV6FspF6bz_vGYE1Qn5GNobEvxEAIME',
    appId: '1:639418752677:android:74322a5393e965c605774c',
    messagingSenderId: '639418752677',
    projectId: 'clipsync-44cea',
    storageBucket: 'clipsync-44cea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFTe1LEnMDcF25kv_4arxig9BFvWmGr2A',
    appId: '1:639418752677:ios:75b8a56939ea0fbf05774c',
    messagingSenderId: '639418752677',
    projectId: 'clipsync-44cea',
    storageBucket: 'clipsync-44cea.firebasestorage.app',
    iosClientId: '639418752677-ua6p0l8so3nij343hn2v7fdkf91oin9p.apps.googleusercontent.com',
    iosBundleId: 'com.erulight.clipSyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbKI6LDUimJvKiBOFd2HFqs-sc7YQI_1w',
    appId: '1:639418752677:web:1eb5047df9c990da05774c',
    messagingSenderId: '639418752677',
    projectId: 'clipsync-44cea',
    authDomain: 'clipsync-44cea.firebaseapp.com',
    storageBucket: 'clipsync-44cea.firebasestorage.app',
    measurementId: 'G-3MH18D2DMC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFTe1LEnMDcF25kv_4arxig9BFvWmGr2A',
    appId: '1:639418752677:ios:75b8a56939ea0fbf05774c',
    messagingSenderId: '639418752677',
    projectId: 'clipsync-44cea',
    storageBucket: 'clipsync-44cea.firebasestorage.app',
    iosClientId: '639418752677-ua6p0l8so3nij343hn2v7fdkf91oin9p.apps.googleusercontent.com',
    iosBundleId: 'com.erulight.clipSyncApp',
  );

}